### ISSUE TITLE
Problem with blank fields

### ISSUE THREAD

**Issue by makeworthymedia** [andersthorborg/ACFDateTimePickerPolyfill#1]
When I activated this I noticed that if I edited a post my custom fields were missing if they hadn't had any content saved in them. And if I tried to create a new post, only the first field would appear and the rest were gone. The error log let me know the problem was on line 56:

[17-Jun-2016 18:17:08 UTC] PHP Fatal error:  Class 'Gejst\ACFDateTimePolyfill\DateTime' not found in /home1/useraccount/public_html/wp-content/mu-plugins/acf-date-time-picker-polyfill.php on line 56

It seems that if the $value sent to "public function load_value" was empty, it was causing the error. If you add code that checks to make sure $value is not empty before creating the $datetime it should fix the problem.

Thanks again for creating this polyfill! It's been extremely helpful!

**Comment by andersthorborg** [comment]
Hi there,

I have simplified the load and format techniquie which should resolve this issue.

Thanks for posting.
